### ISSUE TITLE
[SM - 01] Criação do design da Tela de Login

### ISSUE THREAD

**Issue by RogeanCosta** [RogeanCosta/SendMe#3]
**1.  Criar Apresentação da Logo:**
- [x] Criar divisão retangular alongada de cor acinzentada na parte superior da
tela;
- [x] Adicionar a logo na divisão retangular alongada no canto esquerdo da
mesma;

**2. Criar Painel de Login:**
- [x] Criar uma divisão retangular vertical no centro da tela;
- [x] Adicionar Campo de entrada de texto para digitar o email na divisão
retangular vertical abaixo do símbolo de avatar;
- [x]  Adicionar Campo de entrada de texto para digitar a senha na divisão
retangular vertical um pouco abaixo do campo de entrada de texto para o
email;
- [x]  Adicionar texto hiperlink na divisão retangular vertical logo abaixo do campo
de entrada de texto para digitar a senha com a frase “Esqueci minha senha”;
- [x] Adicionar botão com a palavra “Entrar” na divisão retangular vertical um
pouco abaixo do texto hiperlink;
- [x] Adicionar botão com a palavra “Cadastre-se” na divisão retangular vertical
um pouco abaixo do botão com a palavra “Entrar;

**3. Criar Opção de Ajuda:**
- [x] Adicionar texto hiperlink no canto inferior direito da tela com a palavra “Ajuda”
e ao antes da palavra adicionar um símbolo de interrogação;

**Comment by YasmimL** [comment]
Tela de login criada, mas preferi não colocar a imagem do avatar, creio que é desnecessário e a logo não foi incluída, pois não foi definida ainda.
