### ISSUE TITLE
[SM - 16] Criar Tela de Pagamento

### ISSUE THREAD

**Issue by YasmimL** [RogeanCosta/SendMe#35]
- [x] Criar divisão retangular alongada acinzentada na parte superior da tela;
- [x] Adicionar a logo da loja na divisão retangular no canto esquerdo;
- [x] Adicionar botão de avatar no canto direito da divisão retangular alongada;
- [x] Adicionar símbolo de código de barras na tela, abaixo da divisão retangular;
- [x] Adicionar a frase “Forma de pagamento” ao lado do símbolo de código de barras;
- [x] Adicionar linha horizontal abaixo da frase “Forma de pagamento” e do símbolo. Linha cortará todo o plano horizontal da tela;
- [x] Adicionar botão clicável exclusivo abaixo da linha horizontal;
- [x] Adicionar frase “à vista” ao lado do botão clicável exclusivo;
- [x] Adicionar símbolo cifrão ao lado da frase “À vista”;
- [x] Adicionar botão clicável exclusivo, abaixo do primeiro botão clicável exclusivo;
- [x] Adicionar frase “Cartão de crédito/débito” ao lado do segundo botão clicável exclusivo;
- [x] Adicionar símbolo da empresa “mastercard” ao lado da frase “Cartão de crédito”;
- [x] Adicionar símbolo da empresa “Visa” ao lado do símbolo da empresa “Mastercard”;
- [x] Adicionar símbolo da empresa “American Express” ao lado do símbolo da empresa “Visa”;
- [x] Adicionar símbolo da empresa “Dinner’s club” ao lado do símbolo da empresa “American Express”;
- [x] Adicionar símbolo de Cartão magnético centralizado à esquerda da tela;
- [x] Adicionar a frase “Dados do cartão” ao lado do símbolo de cartão magnético;
- [x] Adicionar linha horizontal abaixo da frase “Dados do cartão” e do símbolo. Linha cortará todo o plano horizontal da tela;
- [x] Adicionar a frase “tipo de cartão” abaixo da linha horizontal;
- [x] Adicionar botão clicável exclusivo abaixo da frase “tipo de cartão;
- [x] Adicionar frase “Crédito” ao lado do botão clicável exclusivo;
- [x] Adicionar botão clicável exclusivo ao lado direito da frase “Crédito;
- [x] Adicionar frase “Débito” ao lado do botão clicável exclusivo;
- [x] Adicionar campo de texto editável abaixo do primeiro botão clicável exclusivo para receber a entrada “número do cartão”;
- [x] Adicionar campo de texto editável abaixo do campo “número do cartão” para receber a entrada “nome impresso no cartão”
- [x] Adicionar campo de texto editável abaixo do campo “nome impresso no cartão” para receber a entrada “validade do cartão”;
- [x] Adicionar campo de texto editável ao lado do campo “validade do cartão” para receber a entrada “CVV”;
- [x] Adicionar campo selecionável em cascata para receber a entrada “Quantidade de parcelas”;
- [x] Adicionar botão com fundo verde centralizado na parte de baixo da tela;
- [x] Adicionar no botão verde a frase “Ir para endereço de entrega”;
- [x] Adicionar botão vermelho ao lado do botão verde;
- [x] Adicionar no botão vermelho a frase “Retornar para o carrinho”.

**Comment by RogeanCosta** [comment]
Adicionando ação da tela pagamento.
